### ISSUE TITLE
Linux Installer Wiki Missing

### ISSUE THREAD

**Issue by ghost** [Yushe/myimouto-plus#1]
Did you manage to grab a copy of the Linux instructions from the original repo before it went down? I don't have a windows computer.

**Comment by Yushe** [comment]
@Youboontoo Sorry but thats lost forever as far as I know.

**Comment by ghost** [comment]
Damn... Guess I'll have to look around on website cachers... Thanks anyways!

**Comment by Yushe** [comment]
@Youboontoo If you do find it please give me a link and I will add it.

**Comment by ghost** [comment]
Here's where I got most of the issues I filed back from:
https://web.archive.org/web/20161001180433/https://github.com/myimouto/myimouto
