### ISSUE TITLE
Setting up local image service

### ISSUE THREAD

**Issue by SightSpirit** [Yushe/myimouto-plus#5]
I recently set up a MyImouto server on Ubuntu Server 14.04 LTS using this repository to great success. However, there are several features that appear to be included for which I have scoured the documentation, the source code, and the Web to find info on setting up, to minimal to no success.

One of these is how to set up a local image service to find similar and duplicate images in the database, a feature that I would love to take advantage of. I believe that ImageMagick has a command for comparing images, so in my server's config.php, I set $local_image_service = "imagemagick." (I also tried "imagick.") I continued to receive the message, "No service selected/no local service."

How would I set up a local image service, like ImageMagick or, alternatively, the findimagedupes utility?

**Comment by Yushe** [comment]
All you can do is look at the code and try the figure out how to set it up.

I'll keep this open just in case anyone else wants to help.

**Comment by arthurmv** [comment]
I can't set up too. I don't know how to do it.

**Comment by Yushe** [comment]
@arthurmv This should help: 

https://web.archive.org/web/20161001182746/https://github.com/myimouto/myimouto/wiki/How-to-install
