### ISSUE TITLE
Upload mp4 file :::  File is an invalid content type: application/octet-stream

### ISSUE THREAD

**Issue by Yutimaco** [Yushe/myimouto-plus#7]
Upload mp4 file error :(

**Comment by ghost** [comment]
You can't upload mp4 files without modifying myimouto.

**Comment by Yutimaco** [comment]
trait PostFileMethods
{
    /**
     * Allowed mime types.
     */
    static protected $MIME_TYPES = [
        'image/jpeg' => 'jpg',
        'image/jpg'  => 'jpg',
        'image/png'  => 'png',
        'image/gif'  => 'gif',
        'video/webm' => 'webm',
        'video/mp4'  => 'mp4',
        'application/x-shockwave-flash' => 'swf'
    ];
    

THAT MIME TYPE
:(

**Comment by arthurmv** [comment]
Hi @Yutimaco! Where can I find this configuration?

> trait PostFileMethods
> {
> /**
> * Allowed mime types.
> */
> static protected $MIME_TYPES = [
> 'image/jpeg' => 'jpg',
> 'image/jpg' => 'jpg',
> 'image/png' => 'png',
> 'image/gif' => 'gif',
> 'video/webm' => 'webm',
> 'video/mp4' => 'mp4',
> 'application/x-shockwave-flash' => 'swf'
> ];
> 
> THAT MIME TYPE
> :(

**Comment by arthurmv** [comment]
I got it upload a video replacing `video/mp4` with `application/octet-stream`, but now I can't get a preview in post page, a text link instead... Maybe I need edit one more file.

**Comment by arthurmv** [comment]
Hi @Yutimaco! I got it a upload video replacing `video/mp4` with `application/octet-stream`, but now I can't get a preview in post page, a text link instead... Maybe I need edit one more file.

**Comment by arthurmv** [comment]
Hi @Yutimaco! I got it a upload video replacing video/mp4 with application/octet-stream, but now I can't get a preview in post page, a text link instead... Maybe I need edit one more file.

> trait PostFileMethods
> {
> /**
> * Allowed mime types.
> */
> static protected $MIME_TYPES = [
> 'image/jpeg' => 'jpg',
> 'image/jpg' => 'jpg',
> 'image/png' => 'png',
> 'image/gif' => 'gif',
> 'video/webm' => 'webm',
> 'video/mp4' => 'mp4',
> 'application/x-shockwave-flash' => 'swf'
> ];
> 
> THAT MIME TYPE
> :(

**Comment by arthurmv** [comment]
Hi @Yutimaco! I got it a upload video replacing `video/mp4` with `application/octet-stream`, but now I can't get a preview in post page, a text link instead... Maybe I need edit one more file.
